#!/bin/bash

#########################################
## slurm
#########################################
#SBATCH --job-name=mn3sn
#SBATCH --output=./proc.log
#SBATCH --partition=all  
##SBATCH --nodelist=r3 
##SBATCH --exclude=r2,r3,r4,r5
#SBATCH --ntasks=1       
#SBATCH --cpus-per-task=1
#SBATCH --gres=gpu:1     
#SBATCH --array=0-84:1  ## start and end indices are included


#########################################
## configuration
#########################################
ARRAY=({0..16}.{0..9..2}e-22)
STEP=5000000
INCR=$(echo "${STEP} / 5000" | bc)
ISO1=-3e-21
DMI1=0.0
AISO="${ARRAY[${SLURM_ARRAY_TASK_ID}]}"


########################################
## paths
########################################
SRC="$(pwd)/"
DATE="$(date +'%y%m%d-%H%M%S')-$(date +%N | cut -c1-6)"  ## date
OUT="${SRC}../data/${SLURM_ARRAY_JOB_ID}/${DATE}-${AISO/\./}/"  ## path output directory
CNFSRC="${SRC}conf/"
CNFOUT="${OUT}conf/"
VAMP="vampire-cuda"
EXCSRC="${SRC}${VAMP}"  ## Vampire executable in source directory
EXCOUT="${OUT}${VAMP}"  ## Vampire executable in source directory
VDC="${SRC}util/vdc/vdc"  ## Vampire to povray converter
META="${OUT}meta/"  ## meta data 
LOG="${OUT}proc.log"       ## logfile with std output


########################################
## prepare input and output
########################################
mkdir -p "$META" "$CNFOUT"
cp ${BASH_SOURCE[0]} $OUT
cp $EXCSRC $EXCOUT
prepCnf $CNFSRC      \
        $CNFOUT      \
        "STEP=$STEP" \
        "INCR=$INCR" \
        "ISO1=$ISO1" \
        "DMI1=$DMI1" \
        "AISO=$AISO"


########################################
## run
########################################
cd $OUT
## run simulation
srun --output="$LOG"                       \
     $EXCOUT --input-file "${CNFOUT}input" \
             --output-file "result"
## create povray file
$VDC --povray --input-file "atoms-coords"
## render spin configuration
NFRAME=$(find ${OUT} -name 'spins-*.inc' -printf '%f\n' |
         sed 's/spins-\([0-9]*\)\.inc/\1/' |
         sort -n |
         tail -1)  ## number of frames
/usr/bin/povray +KFI0 +KFF${NFRAME} -W2000 -H1500 +O${META}/conf-.png ${OUT}spins.pov -D


########################################
## clean
########################################
rm $EXCOUT
##cd $SRC
