#!/bin/bash

#########################################
## slurm
#########################################
#SBATCH --job-name=mn3sn
#SBATCH --output=./proc.log
#SBATCH --partition=all  
##SBATCH --nodelist=r3 
##SBATCH --exclude=r2,r3,r4,r5
#SBATCH --ntasks=1       
#SBATCH --cpus-per-task=1
#SBATCH --gres=gpu:1
#SBATCH --array=0-0:1  ## start and end indices are included


#########################################
## configuration
#########################################
INTEG="llg-heun"
INTEG="monte-carlo"
SIZEX=5.0
SIZEY=5.0
SIZEZ=5.0
STEP=20000
INCR=$(echo "${STEP} / 5000" | bc)
SEED=$SLURM_ARRAY_TASK_ID
TEMP=0.0
ISO1=-7.5e-21
DMI1=8.8e-23
ISO2=$(awk -v x="$ISO1" 'BEGIN{print -1 * x}')
ISO3=$(awk -v x="$ISO1" 'BEGIN{print  1 * x}')
DMI3=$(awk -v x="$DMI1" 'BEGIN{print  1 * x}')
AISO=0.0
DAMP=1.0
## Gamma 5x
ISD1="-1,-1,0"
ISD2="-1,+1,0"
ISD3=" 1, 0,0"
## Gamma 3x
##ISD1="-1,+1,0"
##ISD2="-1,-1,0"
##ISD3=" 1, 0,0"
## coordinate axes
##ISD1="1,0,0"
##ISD2="0,1,0"
##ISD3="0,0,1"
## random
##ISD1="random"
##ISD2="random"
##ISD3="random"
## edit
##ISD1=" 0.684136,  0.729355,  0.000118024"
##ISD2=" 0.289574, -0.957156,  0.000119789"
##ISD3="-0.973708,  0.227798, -0.000231876"

# 2nd shell
DMI1N=$(awk -v x="$DMI1" 'BEGIN{print 1 * x}')
DMI1T=$(awk -v x="$DMI1N" 'BEGIN{print -1 * x}')
DMI2N=$(awk -v x="$DMI2" 'BEGIN{print 1 * x}')
DMI2T=$(awk -v x="$DMI2N" 'BEGIN{print -1 * x}')



########################################
## paths
########################################
SRC="$(pwd)/"
DATE="$(date +'%y%m%d-%H%M%S')-$(date +%N | cut -c1-6)"  ## date
OUT="${SRC}../../data/${SLURM_ARRAY_JOB_ID}/${DATE}-${SLURM_ARRAY_TASK_ID}/"  ## path output directory
CNFSRC="${SRC}conf/sub3/"  # source of configuration files
CNFOUT="${OUT}conf/"  # destination of configuration files
VAMP="vampire-cuda"  # Vampire file base name
EXCSRC="${SRC}${VAMP}"  ## Vampire executable in source directory
EXCOUT="${OUT}${VAMP}"  ## Vampire executable in source directory
VDC="${SRC}util/vdc/vdc"  ## Vampire to povray converter
META="${OUT}meta/"  ## meta data 
LOG="${OUT}proc.log"  ## logfile with std output


########################################
## prepare input and output
########################################
mkdir -p "$META" "$CNFOUT"
cp $EXCSRC ${BASH_SOURCE[0]} $OUT
cp $EXCSRC $EXCOUT
prepCnf $CNFSRC        \
        $CNFOUT        \
        "INTEG=$INTEG" \
        "SIZEX=$SIZEX" \
        "SIZEY=$SIZEY" \
        "SIZEZ=$SIZEZ" \
        "STEP=$STEP"   \
        "INCR=$INCR"   \
        "SEED=$SEED"   \
        "TEMP=$TEMP"   \
        "ISO1=$ISO2"   \
        "DMI1N=$DMI1N" \
        "DMI1T=$DMI1T" \
        "ISO2=$ISO2"   \
        "ISO3=$ISO3"   \
        "DMI3N=$DMI3N" \
        "DMI3T=$DMI3T" \
        "AISO=$AISO"   \
        "DAMP=$DAMP"   \
        "ISD1=$ISD1"   \
        "ISD2=$ISD2"   \
        "ISD3=$ISD3"


########################################
## run
########################################
cd $OUT
## run simulation
srun --output="$LOG"                       \
     $EXCOUT --input-file "${CNFOUT}input" \
             --output-file "result"
## create povray file
$VDC --povray                    \
     --input-file "atoms-coords" \
     --vector-z 0,0,1            \
     --slice 0,1,0,1,0,1         \
     --camera-position 0,0.001,1
## render spin configuration
NFRAME=$(find ${OUT} -name 'spins-*.inc' -printf '%f\n' |
         sed 's/spins-\([0-9]*\)\.inc/\1/' |
         sort -n |
         tail -1)  ## number of frames
povray -W2000              \ 
       -H1500              \
       -D                  \
       +KFI0               \
       +KFF${NFRAME}       \
       +O${META}/conf-.png \
       ${OUT}spins.pov 


########################################
## clean
########################################
rm $EXCOUT
