#!/bin/bash

#########################################
## slurm
#########################################
#SBATCH --job-name=mn3sn
#SBATCH --output=./proc.log
#SBATCH --partition=all  
##SBATCH --nodelist=r3 
##SBATCH --exclude=r2,r3,r4,r5
#SBATCH --ntasks=1       
#SBATCH --cpus-per-task=1
#SBATCH --gres=gpu:1
#SBATCH --array=0-8:1  ## start and end indices are included


#########################################
## configuration
#########################################
SIZEX=5.0
SIZEY=5.0
SIZEZ=5.0
STEP=100000
INCR=$(echo "${STEP} / 5000" | bc)
SEED=$SLURM_ARRAY_TASK_ID
TEMP=0.0
ISO1=-1e-21
DMI1=1e-22
ISO2=$ISO1
DMI2=$(awk -v x="$DMI1" 'BEGIN{print +0 * x}')
ISO3=$(awk -v x="$ISO1" 'BEGIN{print -1 * x}')
AISO=0.0
DAMP=1.0
## Gamma 5x
##ISD1="-1,-1,0"
##ISD2="-1,+1,0"
##ISD3=" 1, 0,0"
## Gamma 3x
##ISD1="-1,+1,0"
##ISD2="-1,-1,0"
##ISD3=" 1, 0,0"
## coordinate axes
##ISD1="1,0,0"
##ISD2="0,1,0"
##ISD3="0,0,1"
## random
ISD1="random"
ISD2="random"
ISD3="random"
## edit
##ISD1="+1,0,-1"
##ISD2="-1,0,-1"
##ISD3=" 0,0, 1"



## 1st shell
DMI1X=$(awk -v dmi="$DMI1" 'BEGIN{print dmi *  0}')
DMI1Y=$(awk -v dmi="$DMI1" 'BEGIN{print dmi * -0.74883345}')
DMI1Z=$(awk -v dmi="$DMI1" 'BEGIN{print dmi *  0.66275822}')
gen_s1() {
  local trnsp=-1
  local sigma=1
  while [[ $# -gt 0 ]]; do
    case "$1" in
     -t|-m)
         [[ $1 == -t ]] && trnsp=1 || sigma=-1
         shift
         ;;
     *)
         break
         ;;
    esac
  done
  awk -v phi="$1" -v t="$trnsp" -v s="$sigma" -v iso="$ISO1" -v dx="$DMI1X" -v dy="$DMI1Y" -v dz="$DMI1Z" '
  BEGIN {
    rad = phi * atan2(0, -1) / 180.0
    dxr = t * s * (dx * cos(rad) - dy * sin(rad))
    dyr = t * s * (dx * sin(rad) + dy * cos(rad))
    dzr = t * dz
    printf "% .12e % .12e % .12e % .12e % .12e % .12e % .12e % .12e % .12e\n",
            iso,  dzr, -dyr,
           -dzr,  iso,  dxr,
            dyr, -dxr,  iso
  }'
}
S1UDEFN=$(gen_s1 0)
S1U120N=$(gen_s1 120)
S1U240N=$(gen_s1 240)
S1UDEFT=$(gen_s1 -t 0)
S1U120T=$(gen_s1 -t 120)
S1U240T=$(gen_s1 -t 240)
S1DDEFN=$(gen_s1 -m 0)
S1D120N=$(gen_s1 -m 120)
S1D240N=$(gen_s1 -m 240)
S1DDEFT=$(gen_s1 -m -t 0)
S1D120T=$(gen_s1 -m -t 120)
S1D240T=$(gen_s1 -m -t 240)
# 2nd shell
DMI2N=$(awk -v x="$DMI2" 'BEGIN{print -1 * x}')
DMI2T=$(awk -v x="$DMI2N" 'BEGIN{print -1 * x}')



########################################
## paths
########################################
SRC="$(pwd)/"
DATE="$(date +'%y%m%d-%H%M%S')-$(date +%N | cut -c1-6)"  ## date
OUT="${SRC}../../data/${SLURM_ARRAY_JOB_ID}/${DATE}-${SLURM_ARRAY_TASK_ID}/"  ## path output directory
CNFSRC="${SRC}conf/sub6/"  # source of configuration files
CNFOUT="${OUT}conf/"  # destination of configuration files
VAMP="vampire-cuda"  # Vampire file base name
EXCSRC="${SRC}${VAMP}"  ## Vampire executable in source directory
EXCOUT="${OUT}${VAMP}"  ## Vampire executable in source directory
VDC="${SRC}util/vdc/vdc"  ## Vampire to povray converter
META="${OUT}meta/"  ## meta data 
LOG="${OUT}proc.log"  ## logfile with std output


########################################
## prepare input and output
########################################
mkdir -p "$META" "$CNFOUT"
cp $EXCSRC ${BASH_SOURCE[0]} $OUT
cp $EXCSRC $EXCOUT
prepCnf $CNFSRC            \
        $CNFOUT            \
        "SIZEX=$SIZEX"     \
        "SIZEY=$SIZEY"     \
        "SIZEZ=$SIZEZ"     \
        "STEP=$STEP"       \
        "INCR=$INCR"       \
        "SEED=$SEED"       \
        "TEMP=$TEMP"       \
        "S1UDEFN=$S1UDEFN" \
        "S1U120N=$S1U120N" \
        "S1U240N=$S1U240N" \
        "S1UDEFT=$S1UDEFT" \
        "S1U120T=$S1U120T" \
        "S1U240T=$S1U240T" \
        "S1DDEFN=$S1DDEFN" \
        "S1D120N=$S1D120N" \
        "S1D240N=$S1D240N" \
        "S1DDEFT=$S1DDEFT" \
        "S1D120T=$S1D120T" \
        "S1D240T=$S1D240T" \
        "ISO2=$ISO2"       \
        "DMI2N=$DMI2N"     \
        "DMI2T=$DMI2T"     \
        "ISO3=$ISO3"       \
        "AISO=$AISO"       \
        "DAMP=$DAMP"       \
        "ISD1=$ISD1"       \
        "ISD2=$ISD2"       \
        "ISD3=$ISD3"


########################################
## run
########################################
cd $OUT
## run simulation
srun --output="$LOG"                       \
     $EXCOUT --input-file "${CNFOUT}input" \
             --output-file "result"
## create povray file
$VDC --povray                    \
     --input-file "atoms-coords" \
     --vector-z 0,0,1            \
     --slice 0,1,0,1,0,1         \
     --camera-position 0,0.001,1
## render spin configuration
NFRAME=$(find ${OUT} -name 'spins-*.inc' -printf '%f\n' |
         sed 's/spins-\([0-9]*\)\.inc/\1/' |
         sort -n |
         tail -1)  ## number of frames
povray -W2000              \ 
       -H1500              \
       -D                  \
       +KFI0               \
       +KFF${NFRAME}       \
       +O${META}/conf-.png \
       ${OUT}spins.pov 


########################################
## clean
########################################
rm $EXCOUT
